version: '3'

services:
  # Nginx
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    links:
      - web

  # サーバ本体
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
